### ISSUE TITLE
Inconsistent treating of CurrentCulture and CurrentUICulture

### ISSUE THREAD

**Issue by dradovic** [jcemoller/culture-switcher#1]
Looking at your code it seems that you are only storing the `CurrentCulture` and then restore that value for the `CurrentUICulture`.

Isn't that an issue? (It would be for me if I was to use the code in this way.)

**Comment by joakimriedel** [comment]
You're correct. However, I'm using this in a project where UICulture and Culture is ensured to always be the same. I'll add tests to ensure this is the case before overwriting.
